name: Frontend CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'apps/frontend/**'
  pull_request:
    branches:
      - main
    paths:
      - 'apps/frontend/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python and dependencies
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install pyyaml
        run: pip install pyyaml
      - name: Validate project name and secrets
        run: python infra/ci-cd/validate_project.py frontend

  build-and-test:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build frontend
        run: echo "No build step for static frontend"

      - name: Run MAMOS Test Automation for Frontend
        run: python infra/ci-cd/mamos_runner.py --project frontend

  deploy-test:
    needs: build-and-test
    runs-on: ubuntu-latest
    environment:
      name: Test
      url: https://test.frontend.aladdin.com
    steps:
      - name: Deploy to Test environment
        run: python infra/ci-cd/mamos_runner.py --project frontend --deploy-env Test
        env:
          RENDER_FRONTEND_TEST_API_KEY: ${{ secrets.RENDER_FRONTEND_TEST_API_KEY }}

  deploy-staging:
    needs: deploy-test
    runs-on: ubuntu-latest
    environment:
      name: Staging
      url: https://staging.frontend.aladdin.com
    steps:
      - name: Manual Approval Required for Staging Deployment
        run: |
          echo "********************************************************************************"
          echo "* MANUAL APPROVAL REQUIRED: Deployment to Staging Environment.                 *"
          echo "*                                                                              *"
          echo "* Please review the changes and approve this deployment in the GitHub Actions  *"
          echo "* interface. This ensures all prerequisites are met before proceeding.         *"
          echo "*                                                                              *"
          echo "* Prerequisites:                                                               *"
          echo "* - All automated tests have passed.                                           *"
          echo "* - Code review for the merged changes is complete.                            *"
          echo "* - Necessary Render Service IDs and API Keys are configured for Staging.      *"
          echo "********************************************************************************"

      - name: Deploy to Staging environment
        run: python infra/ci-cd/mamos_runner.py --project frontend --deploy-env Staging
        env:
          RENDER_FRONTEND_STAGING_API_KEY: ${{ secrets.RENDER_FRONTEND_STAGING_API_KEY }}

  deploy-production:
    needs: deploy-staging
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: https://production.frontend.aladdin.com
    steps:
      - name: Manual Approval Required for Production Deployment
        run: |
          echo "********************************************************************************"
          echo "* MANUAL APPROVAL REQUIRED: Deployment to Production Environment.              *"
          echo "*                                                                              *"
          echo "* Please review the changes and approve this deployment in the GitHub Actions  *"
          echo "* interface. This ensures all prerequisites are met before proceeding.         *"
          echo "*                                                                              *"
          echo "* Prerequisites:                                                               *"
          echo "* - All automated tests have passed.                                           *"
          echo "* - Code review for the merged changes is complete.                            *"
          echo "* - Necessary Render Service IDs and API Keys are configured for Production.   *"
          echo "* - Staging deployment has been successfully verified.                         *"
          echo "********************************************************************************"

      - name: Deploy to Production environment
        run: python infra/ci-cd/mamos_runner.py --project frontend --deploy-env Production
        env:
          RENDER_FRONTEND_PRODUCTION_API_KEY: ${{ secrets.RENDER_FRONTEND_PRODUCTION_API_KEY }}
