
name: Integrations CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'apps/integrations/**'
  pull_request:
    branches:
      - main
    paths:
      - 'apps/integrations/**'

jobs:
<<<<<<< HEAD
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python and dependencies
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install pyyaml
        run: pip install pyyaml
      - name: Validate project name and secrets
        run: python infra/ci-cd/validate_project.py integrations

  build-and-test:
    needs: validate
=======
  build-and-test:
>>>>>>> d0bf634cc7097092c9f8b310978c1908532e8245
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r apps/integrations/requirements.txt

      - name: Run MAMOS Test Automation for Integrations
        run: python infra/ci-cd/mamos_runner.py --project integrations

  deploy-test:
    needs: build-and-test
    runs-on: ubuntu-latest
    environment:
      name: Test
      url: https://test.integrations.aladdin.com
    steps:
      - name: Deploy to Test environment
<<<<<<< HEAD
        run: python infra/ci-cd/mamos_runner.py --project integrations --deploy-env Test
        env:
          RENDER_INTEGRATIONS_TEST_API_KEY: ${{ secrets.RENDER_INTEGRATIONS_TEST_API_KEY }}
=======
        run: echo "Deploying integrations to Test environment..."
        # Add actual deployment steps here, e.g., using environment secrets
        # run: echo "Deploying with secret: ${{ secrets.INTEGRATIONS_TEST_DEPLOY_KEY }}"
>>>>>>> d0bf634cc7097092c9f8b310978c1908532e8245

  deploy-staging:
    needs: deploy-test
    runs-on: ubuntu-latest
    environment:
      name: Staging
      url: https://staging.integrations.aladdin.com
    steps:
<<<<<<< HEAD
      - name: Manual Approval Required for Staging Deployment
        run: |
          echo "********************************************************************************"
          echo "* MANUAL APPROVAL REQUIRED: Deployment to Staging Environment.                 *"
          echo "*                                                                              *"
          echo "* Please review the changes and approve this deployment in the GitHub Actions  *"
          echo "* interface. This ensures all prerequisites are met before proceeding.         *"
          echo "*                                                                              *"
          echo "* Prerequisites:                                                               *"
          echo "* - All automated tests have passed.                                           *"
          echo "* - Code review for the merged changes is complete.                            *"
          echo "* - Necessary Render Service IDs and API Keys are configured for Staging.      *"
          echo "********************************************************************************"

      - name: Deploy to Staging environment
        run: python infra/ci-cd/mamos_runner.py --project integrations --deploy-env Staging
        env:
          RENDER_INTEGRATIONS_STAGING_API_KEY: ${{ secrets.RENDER_INTEGRATIONS_STAGING_API_KEY }}
=======
      - name: Deploy to Staging environment
        run: echo "Deploying integrations to Staging environment..."
        # Add actual deployment steps here, e.g., using environment secrets
        # run: echo "Deploying with secret: ${{ secrets.INTEGRATIONS_TEST_DEPLOY_KEY }}"
>>>>>>> d0bf634cc7097092c9f8b310978c1908532e8245

  deploy-production:
    needs: deploy-staging
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: https://production.integrations.aladdin.com
    steps:
<<<<<<< HEAD
      - name: Manual Approval Required for Production Deployment
        run: |
          echo "********************************************************************************"
          echo "* MANUAL APPROVAL REQUIRED: Deployment to Production Environment.              *"
          echo "*                                                                              *"
          echo "* Please review the changes and approve this deployment in the GitHub Actions  *"
          echo "* interface. This ensures all prerequisites are met before proceeding.         *"
          echo "*                                                                              *"
          echo "* Prerequisites:                                                               *"
          echo "* - All automated tests have passed.                                           *"
          echo "* - Code review for the merged changes is complete.                            *"
          echo "* - Necessary Render Service IDs and API Keys are configured for Production.   *"
          echo "* - Staging deployment has been successfully verified.                         *"
          echo "********************************************************************************"

      - name: Deploy to Production environment
        run: python infra/ci-cd/mamos_runner.py --project integrations --deploy-env Production
        env:
          RENDER_INTEGRATIONS_PRODUCTION_API_KEY: ${{ secrets.RENDER_INTEGRATIONS_PRODUCTION_API_KEY }}
=======
      - name: Deploy to Production environment
        run: echo "Deploying integrations to Production environment..."
        # Add actual deployment steps here, e.g., using environment secrets
        # run: echo "Deploying with secret: ${{ secrets.INTEGRATIONS_TEST_DEPLOY_KEY }}"
>>>>>>> d0bf634cc7097092c9f8b310978c1908532e8245

